import Providers from "./component/Providers";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-mui-color-scheme="dark">
      <body
        suppressHydrationWarning
        className="antialiased bg-[--background] text-[--foreground]"
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}